# Generated by Django 3.0.7 on 2020-07-29 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 13, 47, 16, 959633)),
        ),
    ]
